/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.student_usecase.studentportal_db.StandardDetails;
import com.student_usecase.studentportal_db.StandardDetailsId;
import com.student_usecase.studentportal_db.service.StandardDetailsService;


/**
 * Controller object for domain model class StandardDetails.
 * @see StandardDetails
 */
@RestController("StudentPortal_DB.StandardDetailsController")
@Api(value = "StandardDetailsController", description = "Exposes APIs to work with StandardDetails resource.")
@RequestMapping("/StudentPortal_DB/StandardDetails")
public class StandardDetailsController {

    private static final Logger LOGGER = LoggerFactory.getLogger(StandardDetailsController.class);

    @Autowired
	@Qualifier("StudentPortal_DB.StandardDetailsService")
	private StandardDetailsService standardDetailsService;

	@ApiOperation(value = "Creates a new StandardDetails instance.")
@RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
public StandardDetails createStandardDetails(@RequestBody StandardDetails standardDetails) {
		LOGGER.debug("Create StandardDetails with information: {}" , standardDetails);

		standardDetails = standardDetailsService.create(standardDetails);
		LOGGER.debug("Created StandardDetails with information: {}" , standardDetails);

	    return standardDetails;
	}

@ApiOperation(value = "Returns the StandardDetails instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StandardDetails getStandardDetails(@RequestParam("standardId") String standardId,@RequestParam("standardName") String standardName) throws EntityNotFoundException {

        StandardDetailsId standarddetailsId = new StandardDetailsId();
        standarddetailsId.setStandardId(standardId);
        standarddetailsId.setStandardName(standardName);

        LOGGER.debug("Getting StandardDetails with id: {}" , standarddetailsId);
        StandardDetails standardDetails = standardDetailsService.getById(standarddetailsId);
        LOGGER.debug("StandardDetails details with id: {}" , standardDetails);

        return standardDetails;
    }



    @ApiOperation(value = "Updates the StandardDetails instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StandardDetails editStandardDetails(@RequestParam("standardId") String standardId,@RequestParam("standardName") String standardName, @RequestBody StandardDetails standardDetails) throws EntityNotFoundException {

        standardDetails.setStandardId(standardId);
        standardDetails.setStandardName(standardName);

        LOGGER.debug("StandardDetails details with id is updated with: {}" , standardDetails);

        return standardDetailsService.update(standardDetails);
    }


    @ApiOperation(value = "Deletes the StandardDetails instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteStandardDetails(@RequestParam("standardId") String standardId,@RequestParam("standardName") String standardName) throws EntityNotFoundException {

        StandardDetailsId standarddetailsId = new StandardDetailsId();
        standarddetailsId.setStandardId(standardId);
        standarddetailsId.setStandardName(standardName);

        LOGGER.debug("Deleting StandardDetails with id: {}" , standarddetailsId);
        StandardDetails standardDetails = standardDetailsService.delete(standarddetailsId);

        return standardDetails != null;
    }


    /**
     * @deprecated Use {@link #findStandardDetails(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of StandardDetails instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<StandardDetails> searchStandardDetailsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering StandardDetails list");
        return standardDetailsService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of StandardDetails instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<StandardDetails> findStandardDetails(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering StandardDetails list");
        return standardDetailsService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of StandardDetails instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<StandardDetails> filterStandardDetails(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering StandardDetails list");
        return standardDetailsService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportStandardDetails(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return standardDetailsService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of StandardDetails instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countStandardDetails( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting StandardDetails");
		return standardDetailsService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getStandardDetailsAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return standardDetailsService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service StandardDetailsService instance
	 */
	protected void setStandardDetailsService(StandardDetailsService service) {
		this.standardDetailsService = service;
	}

}

