/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvTop3studentsFromAllStandardsResponse implements Serializable {


    @JsonProperty("ACADEMIC_YEAR")
    @ColumnAlias("ACADEMIC_YEAR")
    private String academicYear;

    @JsonProperty("STANDARD_ID")
    @ColumnAlias("STANDARD_ID")
    private Integer standardId;

    @JsonProperty("STUDENT_ID")
    @ColumnAlias("STUDENT_ID")
    private Integer studentId;

    @JsonProperty("STUDENT_NAME")
    @ColumnAlias("STUDENT_NAME")
    private String studentName;

    @JsonProperty("TEST_ID")
    @ColumnAlias("TEST_ID")
    private Integer testId;

    @JsonProperty("TOTAL_MARKS")
    @ColumnAlias("TOTAL_MARKS")
    private BigDecimal totalMarks;

    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public Integer getStandardId() {
        return this.standardId;
    }

    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return this.studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public Integer getTestId() {
        return this.testId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    public BigDecimal getTotalMarks() {
        return this.totalMarks;
    }

    public void setTotalMarks(BigDecimal totalMarks) {
        this.totalMarks = totalMarks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvTop3studentsFromAllStandardsResponse)) return false;
        final SvTop3studentsFromAllStandardsResponse svTop3studentsFromAllStandardsResponse = (SvTop3studentsFromAllStandardsResponse) o;
        return Objects.equals(getAcademicYear(), svTop3studentsFromAllStandardsResponse.getAcademicYear()) &&
                Objects.equals(getStandardId(), svTop3studentsFromAllStandardsResponse.getStandardId()) &&
                Objects.equals(getStudentId(), svTop3studentsFromAllStandardsResponse.getStudentId()) &&
                Objects.equals(getStudentName(), svTop3studentsFromAllStandardsResponse.getStudentName()) &&
                Objects.equals(getTestId(), svTop3studentsFromAllStandardsResponse.getTestId()) &&
                Objects.equals(getTotalMarks(), svTop3studentsFromAllStandardsResponse.getTotalMarks());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear(),
                getStandardId(),
                getStudentId(),
                getStudentName(),
                getTestId(),
                getTotalMarks());
    }
}
