/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvCountOfStudentsInAcademicsResponse implements Serializable {


    @JsonProperty("STANDARD")
    @ColumnAlias("STANDARD")
    private String standard;

    @JsonProperty("count(STUDENT_ID)")
    @ColumnAlias("count(STUDENT_ID)")
    private BigInteger count_studentId_;

    public String getStandard() {
        return this.standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public BigInteger getCount_studentId_() {
        return this.count_studentId_;
    }

    public void setCount_studentId_(BigInteger count_studentId_) {
        this.count_studentId_ = count_studentId_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvCountOfStudentsInAcademicsResponse)) return false;
        final SvCountOfStudentsInAcademicsResponse svCountOfStudentsInAcademicsResponse = (SvCountOfStudentsInAcademicsResponse) o;
        return Objects.equals(getStandard(), svCountOfStudentsInAcademicsResponse.getStandard()) &&
                Objects.equals(getCount_studentId_(), svCountOfStudentsInAcademicsResponse.getCount_studentId_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStandard(),
                getCount_studentId_());
    }
}
