/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvTestQueryResponse implements Serializable {


    @JsonProperty("CONTACT_NUMBER")
    @ColumnAlias("CONTACT_NUMBER")
    private BigInteger contactNumber;

    @JsonProperty("FATHER_NAME")
    @ColumnAlias("FATHER_NAME")
    private String fatherName;

    @JsonProperty("JOINING_DATE")
    @ColumnAlias("JOINING_DATE")
    private Date joiningDate;

    @JsonProperty("STUDENT_ID")
    @ColumnAlias("STUDENT_ID")
    private Integer studentId;

    @JsonProperty("STUDENT_NAME")
    @ColumnAlias("STUDENT_NAME")
    private String studentName;

    public BigInteger getContactNumber() {
        return this.contactNumber;
    }

    public void setContactNumber(BigInteger contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getFatherName() {
        return this.fatherName;
    }

    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    public Date getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return this.studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvTestQueryResponse)) return false;
        final SvTestQueryResponse svTestQueryResponse = (SvTestQueryResponse) o;
        return Objects.equals(getContactNumber(), svTestQueryResponse.getContactNumber()) &&
                Objects.equals(getFatherName(), svTestQueryResponse.getFatherName()) &&
                Objects.equals(getJoiningDate(), svTestQueryResponse.getJoiningDate()) &&
                Objects.equals(getStudentId(), svTestQueryResponse.getStudentId()) &&
                Objects.equals(getStudentName(), svTestQueryResponse.getStudentName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContactNumber(),
                getFatherName(),
                getJoiningDate(),
                getStudentId(),
                getStudentName());
    }
}