/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * GradeDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`GRADE_DETAILS`")
public class GradeDetails implements Serializable {

    private Integer gradeId;
    private String grade;
    private int maxValue;
    private int minValue;
    private List<Results> resultses;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`GRADE_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    @Column(name = "`GRADE`", nullable = false, length = 2)
    public String getGrade() {
        return this.grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    @Column(name = "`MAX_VALUE`", nullable = false, scale = 0, precision = 10)
    public int getMaxValue() {
        return this.maxValue;
    }

    public void setMaxValue(int maxValue) {
        this.maxValue = maxValue;
    }

    @Column(name = "`MIN_VALUE`", nullable = false, scale = 0, precision = 10)
    public int getMinValue() {
        return this.minValue;
    }

    public void setMinValue(int minValue) {
        this.minValue = minValue;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<Results> getResultses() {
        return this.resultses;
    }

    public void setResultses(List<Results> resultses) {
        this.resultses = resultses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GradeDetails)) return false;
        final GradeDetails gradeDetails = (GradeDetails) o;
        return Objects.equals(getGradeId(), gradeDetails.getGradeId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getGradeId());
    }
}

