/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentAcademics generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`STUDENT_ACADEMICS`")
@IdClass(StudentAcademicsId.class)
public class StudentAcademics implements Serializable {

    private String academicYear;
    private Integer standardId;
    private Integer studentId;
    private int rollNumber;
    private Academics academics;
    private StudentDetails studentDetails;

    @Id
    @Column(name = "`ACADEMIC_YEAR`", nullable = false, length = 255)
    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    @Id
    @Column(name = "`STANDARD_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getStandardId() {
        return this.standardId;
    }

    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    @Id
    @Column(name = "`STUDENT_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Column(name = "`ROLL_NUMBER`", nullable = false, scale = 0, precision = 10)
    public int getRollNumber() {
        return this.rollNumber;
    }

    public void setRollNumber(int rollNumber) {
        this.rollNumber = rollNumber;
    }

    
    
    public Academics getAcademics() {
        return this.academics;
    }

    public void setAcademics(Academics academics) {
        if(academics != null) {
            this.academicYear = academics.getAcademicYear();
            this.standardId = academics.getStandardId();
        }

        this.academics = academics;
    }

    
    
    public StudentDetails getStudentDetails() {
        return this.studentDetails;
    }

    public void setStudentDetails(StudentDetails studentDetails) {
        if(studentDetails != null) {
            this.studentId = studentDetails.getStudentId();
        }

        this.studentDetails = studentDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StudentAcademics)) return false;
        final StudentAcademics studentAcademics = (StudentAcademics) o;
        return Objects.equals(getAcademicYear(), studentAcademics.getAcademicYear()) &&
                Objects.equals(getStandardId(), studentAcademics.getStandardId()) &&
                Objects.equals(getStudentId(), studentAcademics.getStudentId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear(),
                getStandardId(),
                getStudentId());
    }
}

