/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * StudentIdentification generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`STUDENT_IDENTIFICATION`")
public class StudentIdentification implements Serializable {

    private Integer identificationId;
    private String identificationNumber;
    private String identificationType;
    private List<StudentDetails> studentDetailses;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`IDENTIFICATION_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getIdentificationId() {
        return this.identificationId;
    }

    public void setIdentificationId(Integer identificationId) {
        this.identificationId = identificationId;
    }

    @Column(name = "`IDENTIFICATION_NUMBER`", nullable = true, length = 255)
    public String getIdentificationNumber() {
        return this.identificationNumber;
    }

    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    @Column(name = "`IDENTIFICATION_TYPE`", nullable = true, length = 255)
    public String getIdentificationType() {
        return this.identificationType;
    }

    public void setIdentificationType(String identificationType) {
        this.identificationType = identificationType;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<StudentDetails> getStudentDetailses() {
        return this.studentDetailses;
    }

    public void setStudentDetailses(List<StudentDetails> studentDetailses) {
        this.studentDetailses = studentDetailses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StudentIdentification)) return false;
        final StudentIdentification studentIdentification = (StudentIdentification) o;
        return Objects.equals(getIdentificationId(), studentIdentification.getIdentificationId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdentificationId());
    }
}

