/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StudentIdentification generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`STUDENT_IDENTIFICATION`", uniqueConstraints = {
        @UniqueConstraint(name = "`UK_STUDENT_IDENTIFICATIOTdy4I`", columnNames = {"`IDENTIFICATION_NUMBER`"})})
public class StudentIdentification implements Serializable {

    private Integer identificationId;
    private String identificationType;
    private String identificationNumber;
    private StudentDetails studentDetails;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`IDENTIFICATION_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getIdentificationId() {
        return this.identificationId;
    }

    public void setIdentificationId(Integer identificationId) {
        this.identificationId = identificationId;
    }

    @Column(name = "`IDENTIFICATION_TYPE`", nullable = true, length = 255)
    public String getIdentificationType() {
        return this.identificationType;
    }

    public void setIdentificationType(String identificationType) {
        this.identificationType = identificationType;
    }

    @Column(name = "`IDENTIFICATION_NUMBER`", nullable = true, length = 255)
    public String getIdentificationNumber() {
        return this.identificationNumber;
    }

    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.REMOVE, mappedBy = "studentIdentification")
    public StudentDetails getStudentDetails() {
        return this.studentDetails;
    }

    public void setStudentDetails(StudentDetails studentDetails) {
        this.studentDetails = studentDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StudentIdentification)) return false;
        final StudentIdentification studentIdentification = (StudentIdentification) o;
        return Objects.equals(getIdentificationId(), studentIdentification.getIdentificationId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdentificationId());
    }
}

