/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

public class ViewResultsId implements Serializable {

    private String academicYear;
    private Integer standardId;
    private Integer studentId;
    private String studentName;
    private Integer testId;
    private BigInteger totalMarks;

    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public Integer getStandardId() {
        return this.standardId;
    }

    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return this.studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public Integer getTestId() {
        return this.testId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    public BigInteger getTotalMarks() {
        return this.totalMarks;
    }

    public void setTotalMarks(BigInteger totalMarks) {
        this.totalMarks = totalMarks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewResults)) return false;
        final ViewResults viewResults = (ViewResults) o;
        return Objects.equals(getAcademicYear(), viewResults.getAcademicYear()) &&
                Objects.equals(getStandardId(), viewResults.getStandardId()) &&
                Objects.equals(getStudentId(), viewResults.getStudentId()) &&
                Objects.equals(getStudentName(), viewResults.getStudentName()) &&
                Objects.equals(getTestId(), viewResults.getTestId()) &&
                Objects.equals(getTotalMarks(), viewResults.getTotalMarks());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear(),
                getStandardId(),
                getStudentId(),
                getStudentName(),
                getTestId(),
                getTotalMarks());
    }
}
