/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.studentportal_db.Academics;
import com.student_usecase.studentportal_db.AcademicsId;


/**
 * ServiceImpl object for domain model class Academics.
 *
 * @see Academics
 */
@Service("StudentPortal_DB.AcademicsService")
@Validated
@EntityService(entityClass = Academics.class, serviceId = "StudentPortal_DB")
public class AcademicsServiceImpl implements AcademicsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AcademicsServiceImpl.class);


    @Autowired
    @Qualifier("StudentPortal_DB.AcademicsDao")
    private WMGenericDao<Academics, AcademicsId> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Academics, AcademicsId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics create(Academics academics) {
        LOGGER.debug("Creating a new Academics with information: {}", academics);

        Academics academicsCreated = this.wmGenericDao.create(academics);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(academicsCreated);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics getById(AcademicsId academicsId) {
        LOGGER.debug("Finding Academics by id: {}", academicsId);
        return this.wmGenericDao.findById(academicsId);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics findById(AcademicsId academicsId) {
        LOGGER.debug("Finding Academics by id: {}", academicsId);
        try {
            return this.wmGenericDao.findById(academicsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Academics found with id: {}", academicsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public List<Academics> findByMultipleIds(List<AcademicsId> academicsIds, boolean orderedReturn) {
        LOGGER.debug("Finding Academics by ids: {}", academicsIds);

        return this.wmGenericDao.findByMultipleIds(academicsIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics update(Academics academics) {
        LOGGER.debug("Updating Academics with information: {}", academics);

        this.wmGenericDao.update(academics);
        this.wmGenericDao.refresh(academics);

        return academics;
    }

    @Transactional(value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics partialUpdate(AcademicsId academicsId, Map<String, Object>academicsPatch) {
        LOGGER.debug("Partially Updating the Academics with id: {}", academicsId);

        Academics academics = getById(academicsId);

        try {
            ObjectReader academicsReader = this.objectMapper.reader().forType(Academics.class).withValueToUpdate(academics);
            academics = academicsReader.readValue(this.objectMapper.writeValueAsString(academicsPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", academicsPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        academics = update(academics);

        return academics;
    }

    @Transactional(value = "StudentPortal_DBTransactionManager")
    @Override
    public Academics delete(AcademicsId academicsId) {
        LOGGER.debug("Deleting Academics with id: {}", academicsId);
        Academics deleted = this.wmGenericDao.findById(academicsId);
        if (deleted == null) {
            LOGGER.debug("No Academics found with id: {}", academicsId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Academics.class.getSimpleName(), academicsId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "StudentPortal_DBTransactionManager")
    @Override
    public void delete(Academics academics) {
        LOGGER.debug("Deleting Academics with {}", academics);
        this.wmGenericDao.delete(academics);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Academics> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Academics");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Academics> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Academics");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service StudentPortal_DB for table Academics to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service StudentPortal_DB for table Academics to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}