/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.studentportal_db.models.query.*;

@Service
public class StudentPortal_DBQueryExecutorServiceImpl_V1 implements StudentPortal_DBQueryExecutorService_V1 {

    private static final Logger LOGGER = LoggerFactory.getLogger(StudentPortal_DBQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("StudentPortal_DBWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_TestDetails(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_TestDetails", params, Object.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, Date year, String standard) {
        Map params = new HashMap(2);

        params.put("year", year);
        params.put("standard", standard);

        return queryExecutor.executeNamedQuery("SV_AcademicSubjectsByStandard", params, Object.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_ResultsByTestID(Pageable pageable, String tname) {
        Map params = new HashMap(1);

        params.put("T_Name", tname);

        return queryExecutor.executeNamedQuery("SV_ResultsByTestID", params, Object.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_CountOfStudentsInAcademics(Pageable pageable, String standard, Date year) {
        Map params = new HashMap(2);

        params.put("standard", standard);
        params.put("year", year);

        return queryExecutor.executeNamedQuery("SV_CountOfStudentsInAcademics", params, Object.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_StudentAcademicResults(Pageable pageable, Integer studentId) {
        Map params = new HashMap(1);

        params.put("student_id", studentId);

        return queryExecutor.executeNamedQuery("SV_StudentAcademicResults", params, Object.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<Object> executeSV_TestQuery(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_TestQuery", params, Object.class, pageable);
    }

}


