/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.studentportal_db.models.query.*;

@Deprecated
public interface StudentPortal_DBQueryExecutorService_V1 {

    @Deprecated
    public Page<Object> executeSV_TestDetails(Pageable pageable);

    @Deprecated
    public Page<Object> executeSV_ResultsByTestID(Pageable pageable, String tname);

    @Deprecated
    public Page<Object> executeSV_StudentAcademicResults(Pageable pageable, Integer studentId);

    @Deprecated
    public Page<Object> executeSV_TestQuery(Pageable pageable);

    @Deprecated
    public Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, Date year, String standard);

    @Deprecated
    public Page<Object> executeSV_CountOfStudentsInAcademics(Pageable pageable, String standard, Date year);

}


