/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.studentportal_db.models.query.*;

public interface StudentPortal_DBQueryExecutorService {

    Page<SvTestDetailsResponse> executeSV_TestDetails(Pageable pageable);

    Downloadable exportSV_TestDetails(ExportType exportType, Pageable pageable);

    Page<SvAcademicSubjectsByStandardResponse> executeSV_AcademicSubjectsByStandard(Date year, String standard, Pageable pageable);

    Downloadable exportSV_AcademicSubjectsByStandard(ExportType exportType, Date year, String standard, Pageable pageable);

    Page<SvResultsByTestIdResponse> executeSV_ResultsByTestID(String tname, Pageable pageable);

    Downloadable exportSV_ResultsByTestID(ExportType exportType, String tname, Pageable pageable);

    Page<SvCountOfStudentsInAcademicsResponse> executeSV_CountOfStudentsInAcademics(String standard, Date year, Pageable pageable);

    Downloadable exportSV_CountOfStudentsInAcademics(ExportType exportType, String standard, Date year, Pageable pageable);

    Page<SvStudentAcademicResultsResponse> executeSV_StudentAcademicResults(Integer studentId, Pageable pageable);

    Downloadable exportSV_StudentAcademicResults(ExportType exportType, Integer studentId, Pageable pageable);

    Page<SvTestQueryResponse> executeSV_TestQuery(Pageable pageable);

    Downloadable exportSV_TestQuery(ExportType exportType, Pageable pageable);

}


