/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.studentportal_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.studentportal_db.models.query.*;

@Service
public class StudentPortal_DBQueryExecutorServiceImpl implements StudentPortal_DBQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(StudentPortal_DBQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("StudentPortal_DBWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvTestDetailsResponse> executeSV_TestDetails(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_TestDetails", params, SvTestDetailsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_TestDetails(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("SV_TestDetails", params, exportType, SvTestDetailsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvResultsByTestIdResponse> executeSV_ResultsByTestID(String tname, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("T_Name", tname);

        return queryExecutor.executeNamedQuery("SV_ResultsByTestID", params, SvResultsByTestIdResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_ResultsByTestID(ExportType exportType, String tname, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("T_Name", tname);

        return queryExecutor.exportNamedQueryData("SV_ResultsByTestID", params, exportType, SvResultsByTestIdResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvStudentAcademicResultsResponse> executeSV_StudentAcademicResults(Integer studentId, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("student_id", studentId);

        return queryExecutor.executeNamedQuery("SV_StudentAcademicResults", params, SvStudentAcademicResultsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_StudentAcademicResults(ExportType exportType, Integer studentId, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("student_id", studentId);

        return queryExecutor.exportNamedQueryData("SV_StudentAcademicResults", params, exportType, SvStudentAcademicResultsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvTestQueryResponse> executeSV_TestQuery(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_TestQuery", params, SvTestQueryResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_TestQuery(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("SV_TestQuery", params, exportType, SvTestQueryResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvAcademicSubjectsByStandardResponse> executeSV_AcademicSubjectsByStandard(Date year, String standard, Pageable pageable) {
        Map params = new HashMap(2);

        params.put("year", year);
        params.put("standard", standard);

        return queryExecutor.executeNamedQuery("SV_AcademicSubjectsByStandard", params, SvAcademicSubjectsByStandardResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_AcademicSubjectsByStandard(ExportType exportType, Date year, String standard, Pageable pageable) {
        Map params = new HashMap(2);

        params.put("year", year);
        params.put("standard", standard);

        return queryExecutor.exportNamedQueryData("SV_AcademicSubjectsByStandard", params, exportType, SvAcademicSubjectsByStandardResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Page<SvCountOfStudentsInAcademicsResponse> executeSV_CountOfStudentsInAcademics(String standard, Date year, Pageable pageable) {
        Map params = new HashMap(2);

        params.put("standard", standard);
        params.put("year", year);

        return queryExecutor.executeNamedQuery("SV_CountOfStudentsInAcademics", params, SvCountOfStudentsInAcademicsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "StudentPortal_DBTransactionManager")
    @Override
    public Downloadable exportSV_CountOfStudentsInAcademics(ExportType exportType, String standard, Date year, Pageable pageable) {
        Map params = new HashMap(2);

        params.put("standard", standard);
        params.put("year", year);

        return queryExecutor.exportNamedQueryData("SV_CountOfStudentsInAcademics", params, exportType, SvCountOfStudentsInAcademicsResponse.class, pageable);
    }

}


