/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.school_db.EmployeeDetails;


/**
 * ServiceImpl object for domain model class EmployeeDetails.
 *
 * @see EmployeeDetails
 */
@Service("School_DB.EmployeeDetailsService")
public class EmployeeDetailsServiceImpl implements EmployeeDetailsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeeDetailsServiceImpl.class);


    @Autowired
    @Qualifier("School_DB.EmployeeDetailsDao")
    private WMGenericDao<EmployeeDetails, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<EmployeeDetails, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
	public EmployeeDetails create(EmployeeDetails employeeDetails) {
        LOGGER.debug("Creating a new EmployeeDetails with information: {}", employeeDetails);
        EmployeeDetails employeeDetailsCreated = this.wmGenericDao.create(employeeDetails);
        if(employeeDetailsCreated.getEmployeeDetailsesForManagerId() != null) {
            for(EmployeeDetails employeeDetailsesForManagerId : employeeDetailsCreated.getEmployeeDetailsesForManagerId()) {
                employeeDetailsesForManagerId.setEmployeeDetailsByManagerId(employeeDetailsCreated);
                LOGGER.debug("Creating a new child EmployeeDetails with information: {}", employeeDetailsesForManagerId);
                create(employeeDetailsesForManagerId);
            }
        }
        return employeeDetailsCreated;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public EmployeeDetails getById(Integer employeedetailsId) throws EntityNotFoundException {
        LOGGER.debug("Finding EmployeeDetails by id: {}", employeedetailsId);
        EmployeeDetails employeeDetails = this.wmGenericDao.findById(employeedetailsId);
        if (employeeDetails == null){
            LOGGER.debug("No EmployeeDetails found with id: {}", employeedetailsId);
            throw new EntityNotFoundException(String.valueOf(employeedetailsId));
        }
        return employeeDetails;
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public EmployeeDetails findById(Integer employeedetailsId) {
        LOGGER.debug("Finding EmployeeDetails by id: {}", employeedetailsId);
        return this.wmGenericDao.findById(employeedetailsId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "School_DBTransactionManager")
	@Override
	public EmployeeDetails update(EmployeeDetails employeeDetails) throws EntityNotFoundException {
        LOGGER.debug("Updating EmployeeDetails with information: {}", employeeDetails);
        this.wmGenericDao.update(employeeDetails);

        Integer employeedetailsId = employeeDetails.getEmpId();

        return this.wmGenericDao.findById(employeedetailsId);
    }

    @Transactional(value = "School_DBTransactionManager")
	@Override
	public EmployeeDetails delete(Integer employeedetailsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting EmployeeDetails with id: {}", employeedetailsId);
        EmployeeDetails deleted = this.wmGenericDao.findById(employeedetailsId);
        if (deleted == null) {
            LOGGER.debug("No EmployeeDetails found with id: {}", employeedetailsId);
            throw new EntityNotFoundException(String.valueOf(employeedetailsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public Page<EmployeeDetails> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all EmployeeDetails");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<EmployeeDetails> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all EmployeeDetails");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service School_DB for table EmployeeDetails to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<EmployeeDetails> findAssociatedEmployeeDetailsesForManagerId(Integer empId, Pageable pageable) {
        LOGGER.debug("Fetching all associated employeeDetailsesForManagerId");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeeDetailsByManagerId.empId = '" + empId + "'");

        return findAll(queryBuilder.toString(), pageable);
    }


}

