/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.school_db.models.query.*;

@Deprecated
public interface School_DBQueryExecutorService_V1 {

    @Deprecated
    public Page<Object> executeSV_GetSTudentResultsForStandard(Pageable pageable, String academicYear, Integer standardid, Integer testid);

    @Deprecated
    public Page<Object> executeSV_CountOfStudents(Pageable pageable, Integer standard, String year);

    @Deprecated
    public Page<Object> executeSV_Top3StudentsFromAllStandards(Pageable pageable, Integer testid, String academicyear);

    @Deprecated
    public Page<Object> executeSV_AcademicSubjectsByStandard(Pageable pageable, String year, Integer standard);

    @Deprecated
    public Page<Object> executeSV_CountOfStudentPerGrade(Pageable pageable, String academicYear, Integer standardid);

}


