/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.school_db.AcademicTestSubjects;
import com.student_usecase.school_db.TestDetails;


/**
 * ServiceImpl object for domain model class TestDetails.
 *
 * @see TestDetails
 */
@Service("School_DB.TestDetailsService")
@Validated
public class TestDetailsServiceImpl implements TestDetailsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TestDetailsServiceImpl.class);

    @Lazy
    @Autowired
	@Qualifier("School_DB.AcademicTestSubjectsService")
	private AcademicTestSubjectsService academicTestSubjectsService;

    @Autowired
    @Qualifier("School_DB.TestDetailsDao")
    private WMGenericDao<TestDetails, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TestDetails, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
	public TestDetails create(TestDetails testDetails) {
        LOGGER.debug("Creating a new TestDetails with information: {}", testDetails);
        TestDetails testDetailsCreated = this.wmGenericDao.create(testDetails);
        if(testDetailsCreated.getAcademicTestSubjectses() != null) {
            for(AcademicTestSubjects academicTestSubjectse : testDetailsCreated.getAcademicTestSubjectses()) {
                academicTestSubjectse.setTestDetails(testDetailsCreated);
                LOGGER.debug("Creating a new child AcademicTestSubjects with information: {}", academicTestSubjectse);
                academicTestSubjectsService.create(academicTestSubjectse);
            }
        }
        return testDetailsCreated;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public TestDetails getById(Integer testdetailsId) throws EntityNotFoundException {
        LOGGER.debug("Finding TestDetails by id: {}", testdetailsId);
        TestDetails testDetails = this.wmGenericDao.findById(testdetailsId);
        if (testDetails == null){
            LOGGER.debug("No TestDetails found with id: {}", testdetailsId);
            throw new EntityNotFoundException(String.valueOf(testdetailsId));
        }
        return testDetails;
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public TestDetails findById(Integer testdetailsId) {
        LOGGER.debug("Finding TestDetails by id: {}", testdetailsId);
        return this.wmGenericDao.findById(testdetailsId);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public TestDetails getByTestName(String testName) {
        Map<String, Object> testNameMap = new HashMap<>();
        testNameMap.put("testName", testName);

        LOGGER.debug("Finding TestDetails by unique keys: {}", testNameMap);
        TestDetails testDetails = this.wmGenericDao.findByUniqueKey(testNameMap);

        if (testDetails == null){
            LOGGER.debug("No TestDetails found with given unique key values: {}", testNameMap);
            throw new EntityNotFoundException(String.valueOf(testNameMap));
        }

        return testDetails;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "School_DBTransactionManager")
	@Override
	public TestDetails update(TestDetails testDetails) throws EntityNotFoundException {
        LOGGER.debug("Updating TestDetails with information: {}", testDetails);
        this.wmGenericDao.update(testDetails);

        Integer testdetailsId = testDetails.getTestId();

        return this.wmGenericDao.findById(testdetailsId);
    }

    @Transactional(value = "School_DBTransactionManager")
	@Override
	public TestDetails delete(Integer testdetailsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting TestDetails with id: {}", testdetailsId);
        TestDetails deleted = this.wmGenericDao.findById(testdetailsId);
        if (deleted == null) {
            LOGGER.debug("No TestDetails found with id: {}", testdetailsId);
            throw new EntityNotFoundException(String.valueOf(testdetailsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public Page<TestDetails> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TestDetails");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<TestDetails> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TestDetails");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service School_DB for table TestDetails to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<AcademicTestSubjects> findAssociatedAcademicTestSubjectses(Integer testId, Pageable pageable) {
        LOGGER.debug("Fetching all associated academicTestSubjectses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("testDetails.testId = '" + testId + "'");

        return academicTestSubjectsService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AcademicTestSubjectsService instance
	 */
	protected void setAcademicTestSubjectsService(AcademicTestSubjectsService service) {
        this.academicTestSubjectsService = service;
    }

}

