/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class TestDetailsId implements Serializable {

    private String testName;
    private Integer testId;

    public String getTestName() {
        return this.testName;
    }

    public void setTestName(String testName) {
        this.testName = testName;
    }

    public Integer getTestId() {
        return this.testId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestDetails)) return false;
        final TestDetails testDetails = (TestDetails) o;
        return Objects.equals(getTestName(), testDetails.getTestName()) &&
                Objects.equals(getTestId(), testDetails.getTestId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTestName(),
                getTestId());
    }
}