/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.student_usecase.studentresults.controller;

import com.student_usecase.studentresults.StudentResults;
import java.lang.String;
import com.student_usecase.school_db.Results;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/studentResults")
public class StudentResultsController {

    @Autowired
    private StudentResults studentResults;

    @RequestMapping(value = "/insertResults", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public Results insertResults(@RequestParam(value = "academicYear", required = false) String academicYear, @RequestParam(value = "standardId", required = false) int standardId, @RequestParam(value = "subjectId", required = false) int subjectId, @RequestParam(value = "testId", required = false) int testId, @RequestParam(value = "testConductedId", required = false) int testConductedId) {
        return studentResults.insertResults(academicYear, standardId, subjectId, testId, testConductedId);
    }
}
